.gitignore, project/settings.py, providers/org/biorxiv/__init__.py, providers/org/biorxiv/apps.py, providers/org/biorxiv/harvester.py, providers/org/biorxiv/normalizer.py
=> BioRxiv Harvester & Normalizer

providers/org/arxiv/apps.py, providers/org/arxiv/normalizer.py, providers/org/biorxiv/normalizer.py, share/normalize/links.py, share/normalize/tools.py
* add doi to Arxiv normalizer
* import tools instead of links for Arxiv and BioRxiv
=> Update Arxiv Normalizer and BioRxiv import

providers/io/osf/normalizer.py
Delegate appropriately and remove ThroughInstitutions
=> Fix OSF Normalizer to use new correct Association through table

providers/org/ncar/__init__.py, providers/org/ncar/apps.py, providers/org/ncar/harvester.py, providers/org/ncar/normalizer.py, share/models/entities.py, share/models/people.py, share/normalize/oai.py, share/normalize/utils.py
* add harvester/normalizer for NCAR
* small OAI update
* location UrlField --> TextField
* add Affiliations to Entity model
=> NCAR harvester/normalizer and Model Changes

providers/gov/scitech/normalizer.py, requirements.txt, share/normalize/links.py, share/normalize/oai.py
- Parses languages to their ISO language codes.
- Update language field for SciTech normalizer and OAI normalizer.
=> ParseLanguage Link

api/views/elasticsearch.py
To allow anyone to make complicated queries and aggregations
=> Elasticsearch permissions update

api/views/elasticsearch.py
Allows the discover page to filter and query.
=> add csrf_exempt decorator to elastic post

bots/elasticsearch/bot.py
Give it realistic expectations in life.
=> Fix elasticsearch bot

api/views/elasticsearch.py, api/views/workflow.py
Really only elasticsearch ones are kinda useful because they link to all the endpoints that are available
=> Add some API docstrings

project/static/css/login_custom.css, templates/admin/base_site.html
=> Add logo and style to admin login page

share/normalize/links.py
* TryLink
* similar to Maybe
* DateParser
* handle being passed `None`
=> [Feature] TryLink and use run instead of execute

api/views/workflow.py
e.g. `/api/providers?sort=long_title`
=> Allow sorting providers by field

.travis.yml, tests/conftest.py, tests/share/disambiguation/test_creativework.py, tests/share/disambiguation/test_tag.py, tests/share/models/test_change.py, tests/share/models/test_rawdata.py, tests/share/models/test_shareobject.py
Mostly just create a new `Change` each time a model is saved.
=> Fix failing tests.

providers/io/osf/harvester.py
=> Skip OSF projects with 'qatest' tag

providers/org/cogprints/apps.py, providers/org/cogprints/normalizer.py, providers/org/cogprints/subject-mapping.json
Add PLOS defined taxonomy subject areas to Cogprints parser and Normalizer
- Add subjects to cogprints parser
- One more mapping 
- Use the new normalizer in apps.py
=> Normalizer and Subject Parser for Cogprints

docs/elasticsearch.rst, docs/ember_app.rst, docs/harvesters_and_normalizers.rst, docs/index.rst, docs/quickstart.rst
* update SHARE links to point to production
* update the harvester and normalizer docs
* a few small hyperlink usage changes
=> [Feature] docs update

docs/index.rst, docs/share_api.rst
Resolves #383 
* document how to push to SHARE
=> Add SHARE API page to docs

api/views/workflow.py, tests/api/test_v1.py
* Rename test file
* Check that changesets were accepted
=> [Feature] Update v1 normalizer tests

share/management/commands/migrateregistrationapp.py
=> Migrations for provider registration and Pushed data

share/change.py, share/disambiguation.py, share/models/change.py, tests/conftest.py, tests/share/changes/test_change.py
Subset of changes in #429, so we don't have to wait for 2.0.0
=> [SHARE-380] Allow objects to transition generic types

bin/share, providers/com/dailyssrn/normalizer.py, providers/com/figshare/normalizer.py, providers/com/peerj/harvester.py, providers/com/peerj/normalizer.py, providers/gov/nsfawards/harvester.py, providers/io/engrxiv/harvester.py, providers/io/osf/harvester.py, providers/io/osf/preprints/harvester.py, providers/io/osf/registrations/harvester.py, providers/io/psyarxiv/harvester.py, providers/io/socarxiv/harvester.py, requirements.txt, share/bot.py, share/harvest/harvester.py, share/harvest/oai.py, share/management/commands/harvest.py, share/management/commands/migratescrapi.py, share/normalize/links.py, share/tasks.py, tests/share/normalize/test_links.py
* Improve date parser link
* add upper and lower bounds
* `None` causes `ValueError`
* uses dateutil instead of Arrow to parse dates
* breaks on bad dates
* Arrow --> Pendulum
* Add tests for date parser
=> [SHARE-388] [Feature] Update date parser

share/models/validators.py, tests/api/test_normalizeddata.py, tests/api/test_validator.py
* Don't allow concrete model if typed model
* Add validation tests (moved some from `test_normalizeddata.py`)
https://openscience.atlassian.net/browse/SHARE-417
=>  [SHARE-417] [Feature] Update validator

providers/org/crossref/apps.py, providers/org/crossref/normalizer.py, share/normalize/parsers.py
In normalizers, allow choosing a model/schema dynamically, using `ctx` and links and all that.
=> [Feature] Let parser schema be a chain

docs/harvesters_and_normalizers.rst
Make the start up instructions more clear.
=> [Feature] Update start instructions

api/serializers.py, api/views/workflow.py, share/tasks.py, tests/api/test_validator.py, tests/share/models/factories.py
* Fix error when viewing normalized data while not logged in
* Allow robots to set the normalized data task id via API
=> [SHARE-437] [2.0.0] Allow robots to set the task id on normalized data

bin/share
Fix debug tool using new storage format
=> [SHARE-448] Feature/debug data

providers/org/ncar/apps.py, providers/org/ncar/harvester.py, providers/org/ncar/normalizer.py
* Update normalizer
* Fix the harvester that never worked :(
=> [2.0.0] ncar update harvester and normalizer

providers/org/datacite/normalizer.py, providers/org/ncar/normalizer.py, share/normalize/oai.py
* Add patent type for Datacite
* `Maybe` --> `Try` in OAI
=> [2.0.0] Check for deleted status OAI, Datacite, NCAR

tests/share/normalize/factories.py, tests/share/normalize/test_models.py
* Add some tests
* Use copy of node when building the graph
* Stringify passed in ids
* Set `cited_as` to agent name if not defined
=> Add person, org, and intitution disambiguation tests

tests/share/disambiguation/test_agent.py, tests/share/disambiguation/test_creativework.py, tests/share/disambiguation/test_person.py, tests/share/normalize/factories.py, tests/share/normalize/test_models.py
* Contributor
* Creator
* Publisher
* Funder
* Host
* identifiers
* tags on a work normalize
* Person
* Works
* Non-person agents
=> [WIP][2.0.0] Add tests

providers/gov/nih/normalizer.py, providers/gov/scitech/normalizer.py
* `gov.scitech`/`gov.doepages` 
* make email regex stricter
* `gov.nih` 
* filter nil out of pretty much all fields
=> [Feature] Fix misc normalizers

providers/org/datacite/normalizer.py
* don't pass `ctx` to award if no award
* catch value errors caused by improper identifiers
=> [Feature] Tweak datacite normalizer

osf_oauth2_adapter/views.py, project/urls.py, templates/allauth/login_errored_cancelled.html
https://openscience.atlassian.net/browse/SHARE-474
=> [Feature] [SHARE-474] Override allauth login cancelled and errored pages

templates/allauth/login_errored_cancelled.html
`Login Cancelled or Errored` --> `Login Unsuccessful`
=> [SHARE-474][Feature] Update error page language

providers/gov/nih/harvester.py, providers/gov/nih/normalizer.py
** will need to renormalize NIH documents
* Add space to regex because, this:
* Move organization relation from funder to work
=> [SHARE-481][Feature] Update NIH harvester and Normalizer

bots/elasticsearch/bot.py, bots/elasticsearch/util.py, project/settings.py, share/graphql/work.py, tests/share/util/test_bleach.py
Bleach description so that it can be rendered safely.
* Bleach description returned by elastic
* Bleach description returned by graphql
None
https://openscience.atlassian.net/browse/SHARE-470
=> [SHARE-470][Feature] Bleach html for elastic & graphql description

bots/elasticsearch/util.py, share/graphql/work.py
Only description was bleached in https://github.com/CenterForOpenScience/SHARE/pull/548
=> [SHARE-470][Feature] Bleach title in elastic and graphql

providers/gov/clinicaltrials/normalizer.py
Give everything from clinicaltrials.gov the type Registration.
Also fix some date parsing problems in that normalizer.
https://openscience.atlassian.net/browse/SHARE-508
=> [SHARE-508][Feature] Registrations from gov.clinicaltrials.

api/filters.py, api/serializers.py, api/urls.py, api/views/workflow.py
`Change` and `ChangeSet` routes are returning 500s on staging and prod due to JSON API renderer.
=> [SHARE-520][Feature-fix] Remove Change and Changeset routes

api/views/registration.py
Fixes 500s if not logged in; still returns 401 (as expected)
=> [SHARE-520][Feature-fix] Don't try and filter by AnonymousUser

bin/share
Prevent errors when harvesting with bin/share.
=> Check if data is string before decode

share/harvesters/edu_gwu.py, share/sources/edu.gwu/source.yaml
*Can switch to hotfix if preferred*
- Remove commas before casting to int
- Update url for request
=> [SHARE-690][Fix] Fix bugs in GWU Preprints Harvester

share/harvesters/edu_ageconsearch.py
=> [SHARE-689][Fix] Fix bugs in AgEconSearch Preprints Harvester

share/management/commands/fullharvest.py, share/tasks.py
Also allow restarting existing harvest jobs using `manage.py fullharvest` and the "Harvest" button in the admin.
=> [SHARE-734][Feature] Wait for lock to mark HarvestLog "In Progress"

share/sources/edu.triceratops/source.yaml
*Already disabled on production*
Disable `edu.triceratops` in source config.
=> [SHARE-842][Task] Disable edu.triceratops

share/sources/edu.utah/source.yaml
*Already enabled on production*
Utah University fixed their OAI feed.
=> [SHARE-856][Task] Enable Utah University

docs/share_api.rst
https://openscience.atlassian.net/browse/SHARE-823
=> [SHARE-823][Improvement] Mention JSON API at the top of the SHARE API docs

share/sources/za.csir/source.yaml
It seems like they started using DSpace in early March which changed all of their urls.
Add a new source config for za.csir.
=> [SHARE-857][Task] Add a new source config for za.csir

share/transformers/mods.py
Even though it's against the spec 😞 
https://openscience.atlassian.net/browse/SHARE-861
=> [SHARE-861][Improvement] Consider <location><url> an identifier in MODS

share/transformers/mods.py
=> [SHARE-656][Fix] Prevent publishers in mods:name from breaking the transformer

whitepapers/Dates.md
https://openscience.atlassian.net/browse/SHARE-575
=> [SHARE-575][Analysis] Partially unknown dates

api/views/workflow.py, tests/api/test_user_endpoint.py
* Fix the API returning 500s
* Support using the API to sync local source configs with production
* use Django object manager
* add tests for user endpoint
=> [Fix] Fix user endpoint and add tests

share/tasks.py
Index all works which disambiguated, even if they weren't modified by
the submitted graph. Updates to related objects could still require
reindexing the work.
=> [Fix] Index all disambiguated works

share/transform/chain/utils.py, share/transformers/org_swbiodiversity.py, tests/share/util/test_contact_extract.py
https://openscience.atlassian.net/browse/SHARE-832
Symbiota transformer still can't parse all contact information due to site inconsistency. 
* Added new utility function contact_extract
* Add 39 tests for the utility function that cover all different cases for listing contact info.
* Update Symbiota transformer
=> [SHARE-832][Feature]Add Symbiota harvester - (additional dev. 2)

CONTRIBUTING.md
Pulled out of https://github.com/CenterForOpenScience/SHARE/pull/647
Concerns raised in that PR:
> For consistency with jira, should this be Improvement instead of Enhancement?
> Oh, +1. Is there a reason for Enhancement over Improvement?
> Also, should it be Bug instead of Fix? Fix describes the PR, but Bug describes the ticket/issue... meh, language.
=> [Improvement] Add CONTRIBUTING.md

requirements.txt, share/models/base.py, share/models/celery.py
Same as #701 , just a little more.
=> Update django 1.11.4

share/sources/com.arizona.openrepository/source.yaml
* Use mods and disable old config
* Add earliest datestamp
* Add approved list for UA Campus Repository
https://openscience.atlassian.net/browse/SHARE-977
=> [SHARE-977][Improvement] Add approved list for UA Campus Repository

CHANGELOG.md
Backfill CHANGELOG.
* Added 2.10.0 release notes
* Added 2.11.0 release notes
* Added unreleased
=> [SHARE-992][Fix] Backfill CHANGELOG

share/sources/edu.smithsonian/source.yaml
Add set "col_10088_539" to Smithsonian Digital Repository blacklist
=> [Feature][SHARE-982] Update Smithsonian Digital Repository blacklist

api/views/feeds.py
Escaping once is enough. We don't need to do it three times.
https://openscience.atlassian.net/browse/SHARE-994
=> [SHARE-994][Fix] Don't triple-escape atom feed content

share/harvesters/gov_nsfawards.py, share/transformers/gov_nsfawards.py
Get all fields from NSFAwards.
* Update harvester
* Update transformer
Quick spot check to make sure things look right with newly harvested NSFAwards works.
Should note that PIs don't show up in the contributor section because the detail page only show people with a "Contributor" or "Creator" relationship. They are returned by the graph endpoint though so could check the network tab in the console.
=> [SHARE-1002][Improvement] Get all fields from NSFAwards

requirements.txt
https://openscience.atlassian.net/browse/SHARE-1048
=> [SHARE-1048][Fix] Update psycopg to 2.7.3 to avoid local error

share/management/commands/fix_datacite.py
Update the `fix_datacite` command to accept some arguments that will make running it regularly more ouchless.
=> [SHARE-1055][Improvement] Build a better bandaid for duplicate contributors

share/oaipmh/repository.py
Use the magic of subqueries to speed up our OAI-PMH considerably when filtering by `set`
=> [SHARE-1045] Turn SlOAI into WhOAI

share/search/daemon.py
When the indexer daemon gets a timeout error from Elasticsearch, wait and retry several times before dying.
=> [SHARE-1064] Indexer daemon should retry when ES times out

share/sources/edu.utah/source.yaml
Add accepted sets to edu.utah source config.
This change has already been made in production.
https://openscience.atlassian.net/browse/SHARE-1043
=> [SHARE-1043] Update edu.utah accepted sets

share/sources/edu.umassmed/source.yaml
This change has already been made in production.
https://openscience.atlassian.net/browse/SHARE-1044
=> [SHARE-1044] Update UMMS config to use HTTPS

share/models/synonyms.json
Remove subject mappings to 'Other Business' that don't make sense.
Also remove a few duplicate mappings I happened to notice. They weren't causing a problem, but were unnecessary.
=> [SHARE-1065] Remove bad subject mappings to 'Other Business'

share/sources/com.arizona.openrepository/source.yaml, share/sources/edu.asu/source.yaml, share/sources/edu.nau.openknowledge/source.yaml
Add type maps.
https://openscience.atlassian.net/browse/SHARE-1068
=> [SHARE-1068] Add type maps for ASU, UA, and NAU

share/bin/harvest.py, share/bin/ingest.py, share/harvest/base.py, share/harvesters/io_osf.py, share/harvesters/oai.py, share/sources/io.osf/source.yaml, share/transformers/io_osf.py
(Includes changes from #754, will be much smaller once that merges)
Fetch identifiers along with OSF nodes, and map them to identifiers in SHARE.
Because it was useful for debugging, I also added fetching by ID with `sharectl`:
```
sharectl fetch io.osf --ids mst3k
```
=> [SHARE-1061] Get DOI/ARK identifiers from OSF

share/bin/search.py, share/search/daemon.py
When one daemon thread encounters an error, gracefully shut down all daemon threads and let it be restarted. This should prevent the index queue from backing up so much.
=> [SHARE-1025] Daemon slaying

share/harvesters/com_figshare_v2.py
Use `modified_since` instead of `modified_date` as a query param, so date filtering actually works.
See: https://docs.figshare.com/#articles_list
=> [SHARE-1075] Fix figshare harvester date range

share/harvesters/io_osf.py
Sometimes OSF nodes are deleted or made private in the middle of a harvest, which breaks that day's harvest. This happens often, and is probably why we're missing so many OSF projects in SHARE.
When fetching embedded lists causes a 401 or 410 error, skip that node and casually continue the harvest.
=> [SHARE-1082] Handle OSF harvest errors

share/harvesters/gov_nsfawards.py
Update the NSF harvester -- when harvesting today's data, looks several days back, too. Records appear to be posted on the next business day, so harvesting on Monday means we have to filter to Friday's data. Assuming the same is true over long holiday weekends, just harvest 5 days back.
Also set `datestamp` on the harvested datums.
=> [SHARE-1035] Update NSF harvester to look back farther

share/transform/chain/exceptions.py, share/transform/chain/links.py, share/transform/chain/parsers.py, share/transformers/io_osf_registrations.py
- Added context to transformer errors, to make this bug (and all future transformer bugs) easier to track down.
- Fix `io.osf.registrations` transformer
=> [SHARE-1089] Fix OSF registrations transformer

share/admin/__init__.py, share/management/commands/format_metadata_records.py, share/search/daemon.py, share/search/index_strategy/sharev2_elastic8.py, share/tasks/__init__.py, templates/admin/start-ingest.html, tests/share/tasks/test_schedule_reingest.py
* exclude fewer suids in `schedule_index_backfill`
* clearer error/log messages to help with debugging
* add admin form to start re-ingest for a given source config
=> address a gappy backfill

trove/vocab/osfmap.py
added description to institution response
=> [ENG-6775] Added description to institution response

trove/vocab/osfmap.py
Ticket https://openscience.atlassian.net/browse/ENG-6775
=> [ENG-6775] Refactored link and link text as separate variables

trove/render/simple_csv.py, trove/util/trove_params.py
Allow fields[*]
https://openscience.atlassian.net/browse/ENG-7446
=> [ENG-7446] Allow fields[*]
