CenterForOpenScience/SHARE

docs/share_models.rst

Followed the Awards example to create Venue example so that there is no ambiguity.  Followed format precisely - including use of "venue" and "venues" following the different use of "award" and "awards".  This change made assuming the earlier instruction "syntax follows the awards example" is literal.  If this is correct, I can repeat addition for funders, institutions, and organizations so that all are explicit.

Added examples of Venue classes + trivial style edits

---

templates/rest_framework/api.html

Add link in API header that goes to http://share-research.readthedocs.io/

Link back to docs in API header

---

api/views/workflow.py

The provider API endpoint should just show providers, but elasticsearch and automerge bots are in there too. Also filter for bots that don't have a name as those are not Provider bot users!

Also exclude robots with no long title as these are processing bots

---

providers/org/crossref/harvester.py
providers/org/crossref/normalizer.py

h/t to @kjw for improving CrossRef's metadata docs so the normalizer could easily be improved 🎉 
- Normalize additional data in the ```Extra``` class.
- Normalize contributor ORCIDs as ```Identifiers```
- Fix ```cited_name``` by making 'given' a ```Maybe```
- Normalize funder and award information.
Closes #259

CrossRef Fixes and Additions

---

share/management/commands/harvest.py

For local testing harvesters that may not have content in a one day period, allow the option to pass in a date for start and end. 
```python manage.py harvest edu.mit --start 2016-07-01```
```python manage.py harvest edu.mit --start 2016-05-01 --end 2016-06-01```

Add start and end options as well as days back for harvesting

---

osf_oauth2_adapter/apps.py
project/settings.py

Use `osf.users.profile_read` instead of `osf.users.all_read`, following CenterForOpenScience/osf.io@84dacefc77768a6f20220cd87984c8557e4b493d

Rename oauth scope to match OSF

---

share/models/base.py
share/models/core.py
share/models/fields.py
tests/share/models/test_datetimeawarejsonfield.py

@icereval @chrisseto This upgrades the JSONField to be compatible with datetime, date, time, and Decimal. It's fairly obvious how to add other formats. Line 22 and Line 35 show encoding and decoding, respectively. This is NOT compatible with the current format and since we're wiping the DB (and it would be very nearly impossible) I didn't write a migration. Datetimes are currently stored as epoch so.... Finding them and re-encoding them to this new format would be hard.

Change DatetimeAwareJSONField to properly encode/decode things

---

api/views/feeds.py
bots/elasticsearch/bot.py
bots/elasticsearch/tasks.py

* Sort contributors by `order_cited` (fixes #343)
* Sort suggestions based on how useful they seem (shorter, more alphabety strings are better) (fixes #342)
* More human-friendly field names for easier query composition (helps resolve #340, #345)
* allows queries like `contributor:einstein AND title:giraffes`
* available fields: `title`, `description`, `source`, `tag`, `language`, `date`, `award`, `venue`, `contributor`, `funder`, `publisher`, `institution`, `organization`
For local dev installs, rebuild the elastic index after pulling:
```
curl -XDELETE 'http://localhost:9200/share'
./manage.py runbot elasticsearch --last-run=0
```

ES mapping changes (don't merge until we can reindex)

---

.travis.yml
setup.cfg

Related to #371 
Note: I don't have admin access on this repository so the travis build needs to be enabled

Add travis file to run python tests and flake8

---

api/serializers.py
api/views/workflow.py
share/models/change.py

Add query params `object_id` and `object_type` to the `/api/rawdata` endpoint. When both are given, returns all `RawData` objects associated with the specified object.
Also, set `change.target_id` when a new object is created from an accepted `Change`.

RawData for a given ShareObject

---

share/change.py
share/disambiguation.py

- If something is ever disambiguated to another type, update references to it in the `ChangeGraph` accordingly.
- Make sure the above never happens by passing `model` into all disambiguators, so `AbstractCreativeWorkDisambiguator` won't match a Preprint with a Project, for instance.

Don't disambiguate across types

---

README.md
docs/harvesters_and_normalizers.rst
docs/quickstart.rst

`docker-compose up -d rabbitmq postgres` --> `docker-compose up -d web`
* README
* Quickstart guide
* Start up for harvesters

Update docker-compose instructions in docs

---

providers/gov/clinicaltrials/normalizer.py
share/disambiguation.py
share/models/change.py

- Make sure we always have a title for gov.clinicaltrials documents
- Turns out `model.objects.filter(**{})` returns everything, don't disambiguate like that (this is probably why work `1` is so messed up)
- Don't try to resolve insert conflicts using `'_:xyz'` ids (caused problems on clinical trials with hundreds of venues)

[hotfix] Handle clinical trials better.

---

share/models/fields.py
tests/share/util/test_model_generator.py

`ModelGenerator` didn't seem to be creating `ShareManyToManyField`s (e.g. `Funder` was missing `awards`), so I looked into it. Turns out django-typed-models modifies `_meta.get_fields()` on typed subclasses to filter out fields that don't belong, based on the fields given in the model definition. Share related fields (`ShareManyToManyField`, etc.) don't directly contribute to classes, they make instances of their base class that contribute instead. Since those don't equal the field defined on the model, they're filtered out of `get_fields`.
This adds a `ShareRelatedField` base class that keeps track of the fields that do a Share field's job, and compares equal to any of them, so they'll be accessible to the normalizers, validator, and whatever else needs it.

[Fix][2.0.0] Un-hide Share relation fields in typed subclasses

---

dev-requirements.txt

`ipdb` is required for running `./bin/share` commands
Note: cherry-picked from Christina #489

[Feature] Add ipdb to dev-requirements

---

share/normalize/parsers.py
tests/share/normalize/test_json.py
tests/share/normalize/test_xml.py

When parsing a string value, remove leading/trailing white space and replace tabs, newlines, multiple spaces, etc. with a single space.

[SHARE-428][Feature][2.0.0] Normalize white space when parsing

---

providers/gov/usgs/normalizer.py
share/normalize/links.py
share/normalize/parsers.py
tests/share/normalize/test_links.py

Also:
- Add `SourceID` to normalizer tools.
- For sources that give objects IDs that aren't URI-like or globally unique, make a URN that `IRI` will recognize.
- Change `OAILink` to `URNLink`, which can accept URNs with scheme `urn` or `oai`
- e.g. `SourceID(ctx.contributorID)` in the `gov.usgs` normalizer yields something like `urn:share:gov.usgs:1234`
- Make sure `Context().parser` is always reset when leaving a parser, even if leaving via exception
- Allows wrapping `Try` around `Delegate`.

[2.0.0] Update USGS normalizer

---

providers/org/dataone/harvester.py
providers/org/dataone/normalizer.py
share/normalize/links.py
tests/share/normalize/test_links.py

- Update DataOne normalizer for 2.0.0
- Add `ARKLink`, since many DataOne identifiers are [ARKs](https://en.wikipedia.org/wiki/Archival_Resource_Key)
- Handle URLs that start with `www.` instead of a scheme, because that happens
- Add `Documents` work relation, but leave the migration off because it's covered by #497

[2.0.0] Updated DataOne normalizer

---

share/normalize/normalizer.py
share/normalize/oai.py

Remove strings that are empty, just white space, 'none', or 'empty'.

[2.0.0] Remove empties from a document before normalizing

---

share/change.py
share/disambiguation.py
share/models/agents.py
share/models/creative.py
share/models/identifiers.py
share/models/meta.py
share/models/relations/agent.py
share/models/relations/agentwork.py
share/models/relations/creative.py
tests/share/disambiguation/test_prune.py

- find and prune duplicates within a graph
- find matching instances in the database

[WIP][2.0.0] Feature/generic disambiguator

---

share/disambiguation.py
share/models/agents.py
share/models/creative.py
share/models/identifiers.py
share/models/meta.py
share/models/relations/agent.py
share/models/relations/agentwork.py
share/models/relations/creative.py
tests/share/disambiguation/test_prune.py
tests/share/normalize/test_models.py

Define disambiguation behavior by adding a `Disambiguation` class to each model.
```python
class Disambiguation:
all = ('field1', 'field2')
any = ('field3', 'field4')
```
In order for two nodes to be considered duplicates, their `field1` and `field2` must be equal, and at least one of `field3` and `field4` must be equal.
TODO: lots more tests, there are many corners to explore

[WIP][2.0.0] Feature/disambigrelation

---

share/disambiguation.py
share/models/identifiers.py

- Filter emails from the default `*Identifier` managers
- Add `objects_unfiltered` manager for the disambiguator to use

[Feature] Filter out emails at the Identifier manager

---

share/disambiguation.py
tests/share/disambiguation/test_agent.py

When disambiguating returns multiple instances, check how many of them are of the type we're looking for. If there's exactly one, use that instance. Otherwise, fail as before.
Lets the system function when a person has the same name as an organization/institution/consortium.

Handle multiple disambiguation results when only one matches type.

---

manage.py
share/tasks.py

* Setting the env variable GEVENT=1 patches everything
* Celery must be run with -P gevent
* Deployments may now run a single harvester worker gevented to ~15
greenlets
* Forced LoggedTask and subclasses to be threadsafe

[SHARE-519][Feature] Allow Celery workers to be run in Gevent mode

---

providers/org/zenodo/apps.py
providers/org/zenodo/datacite/apps.py
providers/org/zenodo/datacite/migrations/0001_initial.py

Only have Zenodo appear in sources once.
* Removed new user creation from zenodo.datacite migration
* Moved user definition from zenodo to zenodo.datacite
* Add `disabled = True` to zenodo
None from this PR
The org.zenodo.datacite user has been deleted from staging which also deleted all of the data harvested by org.zenodo.datacite. The results still show up in elastic and 404 if clicked on.

[SHARE-393][Feature] Update Zenodo migrations so new user is not created

---

share/harvest/oai.py

Prevents Zenodo from failing when there are resumption tokens.

[SHARE-393][Feature] Remove set query param when using resumption token

---

api/urls.py
api/views/schema.py
api/views/share.py
share/util.py

Provide a simple way to get all of the creative work types.
Add `modeltypes` endpoint that returns the contents of `creative.yaml`.
None

[SHARE-465][Feature] Add endpoint for model types

---

api/renderers.py
api/urls.py
share/models/creative.yaml
share/models/meta.py
share/models/relations/agent.yaml
share/models/relations/agentwork.py
share/models/relations/creative.yaml
share/util.py
tests/api/test_generated_endpoints.py
tests/api/test_providerregistration.py

Show encoded ids in API instead of pks.
* Override `extract_relationships` from `JSONAPIRenderer`
* Update generated endpoint tests
None

[SHARE-520][Feature] Encode all ids in API results

---

providers/edu/utah/apps.py

Update the OAI feed url for Utah University.
* update the URL
* update the set_spec
Only one set spec is allowed. Would be better to harvest `ir_space` in its entirety (~300).

[SHARE-541][Feature] Update Utah University feed

---

share/models/creative.yaml

`Repositorys` --> `Repositories`

[SHARE-520][Feature] Correct verbose_name_plural for repository type

---

share/graphql/work.py

Sort contributors by `order_cited` in graphql endpoint, `None` last, so creators are listed in order on the work detail page, followed by all other contributors.
https://openscience.atlassian.net/browse/SHARE-572

[SHARE-572][Feature] Order contributors by order_cited in graphql.

---

providers/org/crossref/harvester.py
share/harvest/harvester.py
share/tasks.py

So it doesn't break when harvesting more than 10k records.
Also, keep only a list of RawData IDs when harvesting, not all the RawData instances.
https://openscience.atlassian.net/browse/SHARE-529
https://openscience.atlassian.net/browse/SHARE-590

[SHARE-529][SHARE-590][Feature] Use cursor, not offset, in Crossref harvester.

---

Dockerfile
api/urls.py
api/views/share.py
project/settings.py
templates/rest_framework/api.html
tests/api/test_status.py

* In DEBUG mode, if VERSION is not set it will be pulled from a git
repo
* The Dockerfile now accepts GIT_TAG which will be passed in as
VERSION
* Also removes "Notify" from browsable API page title

[SHARE-497][SHARE-526][Task] Add a status/version endpoint to the API

---

share/change.py
share/disambiguation.py
share/models/change.py
tests/share/changes/test_merge.py
tests/share/disambiguation/test_prune.py
tests/share/normalize/test_normalize.py

Fixes a bug in merging.
If two works exist in the database:
* WorkA, with IdentifierA and TagA
* WorkB, with IdentifierB and TagB
Then adding a work with two identifiers (IdentifierA, IdentifierB) and two tags (TagA, TagB) will fail. It will correctly try to merge WorkA and WorkB, but the task fails adding a ThroughTag that is already created as part of the merge.
No longer.

[Feature][Fix] Disambiguate relations using all matched instances

---

bots/elasticsearch/bot.py

Currently titles are tokenized and the non-analyzed title is not available via elastic.
Add exact field for title
Requires reindexing but since it's only adding a field, does not require a new index.

[SHARE-643][Improvement] Add exact field for title

---

share/disambiguation.py
share/models/change.py
tests/share/changes/test_merge.py

Make disambiguation and merging more resilient when accepting changesets that (a) trigger a merge and (b) include objects related to the objects to be merged. For example:
- Given a work that has a contributor without an identifier: Push the work's payload a second time with an identifier on its contributor that causes the agent to merge.
- Given two works that have the same tag: Push one of the works a second time (including its tags) with a new identifier that causes the works to merge.
- Don't stop disambiguating a node after it's matched one instance. It could match something else on a subsequent pass.
- When accepting a change, follow `target.same_as` in case it was merged into something else earlier in the changeset.
- Don't emit merge nodes for objects that will be implicitly …

[SHARE-538][Feature][Fix] Fix some merging errors.

---

api/views/workflow.py
bots/elasticsearch/tasks.py
share/graphql/query.py

Display trusted users as sources on the 'Sources' page.
* Update the autocomplete on the sources page (requires the reindexing)
* Switch all instances of filtering by robot='' to favicon=''
The logic for which sources appear in the sources list (only on the sources page) changed. It is hard to tell which ones will appear on the production data set since it is based on each ShareUser's settings.
These updates require the ShareUsers to be reindexed in elasticsearch.

[SHARE-653][Improvement] Display trusted users and robots on sources page

---

share/sources/com.figshare/source.yaml

Remove version from figshare's long_title

---

share/harvesters/oai.py
share/management/commands/oaisources.py

Add `oaisources` command, which can list all OAI sources that have a given prefix in their `ListMetadataFormats` results. It's slow, and could be sped up considerably by making requests in parallel, if anyone ever feels like it.
```
$ ./manage.py oaisources --prefix=datacite
org.datacite (http://oai.datacite.org/oai)
org.zenodo (https://zenodo.org/oai2d)
```
I made this while working on #602, and it might be useful to prioritize transformers based on how often formats are used.

List sources that support a given prefix

---

api/serializers.py
api/views/workflow.py
tests/api/test_readonly_endpoints.py

RawData endpoint was returning 500s.
Updated `viewset` and `serializer` to reflect model changes.
Add status and not being able to push tests for:
- `/rawdata/`
- `/sources/`
- `/site_banner/`

[SHARE-741][Bug] Update raw data endpoint

---

share/sources/edu.columbia/source.yaml

Columbia University Libraries OAI feed has been broken for months. They were contacted.

[SHARE-817][Task] Disable edu.columbia harvester

---

api/urls.py
api/views/elasticsearch.py
tests/api/test_elasticsearch.py
tests/bots/test_elastic.py
tests/conftest.py

Handle elasticsearch scroll API requests.
~~* Return `501` response if scroll requested
* *also considered 400 and 403, thoughts?*~~
* Return `403` response if any improper search request is made 
* Add tests for es scroll API
None
https://openscience.atlassian.net/browse/SHARE-563

[SHARE-563][Bug] Handle scroll api 500s

---

share/oaipmh/repository.py
tests/share/test_oaipmh.py

Use an ordered queryset (by id ascending) for consistent pagination. Take advantage of that to put a cursor in the resumption token for faster page loads.
Also add tests for better coverage.

[Feature] Order OAI records by id, use cursor pagination

---

share/sources/edu.utuskegee/source.yaml

*Disabled on production*
Disable Tuskegee University harvester because they have "localhost" in their identifiers.

[SHARE-845][Task] Disable Tuskegee University

---

share/sources/gov.pubmedcentral/source.yaml

*Already disabled on production*
Both source configs are enabled for PubMed Central which is unnecessary.

[SHARE-847][Task] Disable PubMed Central oai_dc config

---

share/sources/edu.utah/source.yaml

*Already disabled on production*
Disable University of Utah harvester. OAI endpoint is returning `Bad Argument` error for all verbs.

[SHARE-844][Task] Disable University of Utah

---

share/sources/info.spdataverse/source.yaml

*Already disabled on production*
* Update the old urls 
* Disable because the new urls don't quite work right

[SHARE-850][Task] Disable Scholars Portal Dataverse

---

requirements.txt

The upgraded Django REST Framework has optional dependencies to render markdown. We have now opted for them.
https://openscience.atlassian.net/browse/SHARE-858

[SHARE-858][Fix] Browsable API docs not rendering markdown

---

share/harvesters/com_mendeley_data.py

On the last page there wouldn't be a next link but there would be links. 
Catch KeyError instead of checking for presence of links.

[SHARE-315][Feature] Catch KeyError for next link

---

share/transform/chain/utils.py
share/transformers/mods.py
share/transformers/org_datacite.py
tests/share/util/test_force_text.py

Update `force_text` to optionally join lists of strings with a given separator.

[Fix] Backward-compatible force_text

---

api/serializers.py
api/views/workflow.py
dev-requirements.txt
project/settings.py
tests/api/test_readonly_endpoints.py
tests/api/test_sources_endpoint.py
tests/conftest.py

1. Should update be supported for icons only? The way the system currently works, updating the `long_title` would not be desirable. Is allowing updates to just the icon worth implementing?
2. Is using `long_title` submission to create the other username/label/name the best solution? 
Allow creation of a source with the API.
See, https://openscience.atlassian.net/browse/SHARE-876
* Add `create()` method to `sources/` endpoint which creates ShareUser, Source, and SourceConfig.
* Add `is_trusted` to `ShareUserSerializer` so that trusted users can be created.
* The OSF user will need to have the `add_source` permission.
```json
{
"data": {
"type": "Source",
"attributes": {
"homePage": "http://super.test.edu",  (optional)
"longTitle": "Super Test",
"icon": "<url_for_icon>"
}
}
}
```
```json
{ …
```

[SHARE-876][Feature] Allow source creation via API

---

share/transform/chain/links.py

https://openscience.atlassian.net/browse/SHARE-828
Some of our regexes use a deprecated syntax that breaks in python 3.6
Deprecations can be found by running python -Wa manage.py
We need to upgrade to python 3.6
- Remove \B from regex for both ISNI and DOI.
- Run **test_isni_link** and **test_doi_link** under tests/share/normalize/test_links and make sure all tests pass.

[SHARE-828][Feature]Update deprecated regex to support Python 3.6

---

api/users/views.py
share/util/__init__.py

`IDObfuscator.encode` used `type()` to get the model of an instance, which broke on the `SimpleLazyObject` wrapper Django uses for users. Instead, use `instance._meta`, which is proxied to the wrapped object, and should work equivalently for all models.

[Fix] Fix 500 error at /userinfo/ endpoint

---

bots/elasticsearch/bot.py
share/search/fetchers.py
tests/share/search/test_indexing.py

Look at a work's `IsPartOf` relationship as its parent work, and include the closest three ancestors in elasticsearch at `lists.lineage`.
Given several works with lineage:
```
Deeply > Nested > Components > To > Make > A > Good > Long > Lineage
```
The "Long" work will be indexed with:
```
"lineage": [
{   
"identifiers": [
"urn://share/io.osf:83u96",
"http://staging-api.osf.io/v2/nodes/83u96/",
"http://staging.osf.io/83u96/"
],  
"type": "project",
"title": "Make",
"types": [
"project",
"publication",
"creative work"
],  
"id": "3314A-94F-6B8"
},  
{   
"identifiers": [
"urn://share/io.osf:3zmxy",
"http://staging-api.osf.io/v2/nodes/3zmxy/",
"http://staging.osf.io/3zmxy/"
],  
"type": "project",
"title": "A",
"types": [
"project",
"publication",
"creative work"
],  
"id": "3306B-E73-7C9" …
```

[SHARE-1000][Feature] Add lineage to works in the search index

---

CHANGELOG.md
share/sources/edu.columbia/source.yaml

Enable Columbia's harvester. It's already enabled on production but we need to keep production and the config in sync.
https://openscience.atlassian.net/browse/SHARE-518

[Improvement][SHARE-518] Enable edu.columbia harvester

---

share/search/fetchers.py

Once the query reached a certain number of joins, Postgres would (apparently) do all the joins for every work in the database, then apply the `WHERE` filter after the fact.
This change explicitly filters the works in a subquery before joining anything to it, so Postgres doesn't have the power to make such bad life choices.

[SHARE-1000][Fix] Speed up fetch query in indexer

---

share/search/__init__.py
share/tasks.py
tests/share/search/test_indexer.py

When a work is updated (in the `disambiguate` task), reindex its children children (based on `IsPartOf` relations) and any works it retracts, since the work could be included in the elastic payload for those related works.
https://openscience.atlassian.net/browse/SHARE-1000

[SHARE-1000][Fix] When a work is updated, also reindex related works

---

share/sources/edu.scholarsarchiveosu/source.yaml

Update the source config for edu.scholarsarchiveosu. 
* The old config has been disabled on production since it just errors every time.
* Tested locally
* Once added to staging need to run `python manage.py loadsources edu.scholarsarchiveosu` (no need for `--overwrite` since the old config has been disabled already)

[SHARE-1013][Improvement] Update edu.scholarsarchiveosu source config

---

api/views/feeds.py
tests/api/test_feeds.py
tests/factories/share_objects.py

Add authors to atom feed.
See "item_author_name" in https://docs.djangoproject.com/en/1.11/ref/contrib/syndication/#feed-class-reference. RSS doesn't support more than one author on the feed and it's really [supposed to be an email](http://www.rssboard.org/rss-specification#ltauthorgtSubelementOfLtitemgt).
Before:
```xml
<entry>
<title>David's private project</title>
<link href="http://localhost:8000/share/project/15038-C08-6B2" rel="alternate"/>
<updated>2017-09-08T18:22:06+00:00</updated>
<id>http://localhost:8000/share/project/15038-C08-6B2</id>
<summary type="html"/>
<category term="project"/>
</entry>
<entry>
<title>Hello</title>
<link href="http://localhost:8000/share/project/151AE-1EA-BC3" rel="alternate"/>
<updated>2017-09-08T18:22:06+00:00</updated> …
```

[SHARE-1008][Improvement] Add author to atom feed

---

project/settings.py

Avoid an apparent connection leak by using (and closing) a separate DB connection for each request.

[SHARE-1019][Fix] Disable persistent DB connections

---

project/settings.py
share/harvesters/io_osf.py

*Requires that devops adds the `BYPASS_THROTTLE_TOKEN` as an environment variable on prod. Michael has been notified.* ✅  this has been done
OSF harvest tasks fail, every day. We are getting 429s from the OSF API.
Add no throttle header 
Doesn't need QA.

[SHARE-1007][Fix] Add x-throttle-token header to OSF harvester

---

CHANGELOG.md
api/base/views.py
api/util.py
project/settings.py
share/management/commands/fixpreprintdisambiguations.py

Use django's `request.build_absolute_uri` to build URLs in the API instead of SHARE_API_URL. 
SHARE_API_URL is intended for internal access to the API.
Also, add a `--from` parameter to `fixpreprintdisambiguations`, to allow narrowing its scope a little.

[SHARE-1029][Hotfix] Correct links in API

---

CHANGELOG.md
share/sources/edu.columbia/source.yaml

Columbia University asked us to map some types.
* Add type mapping for Columbia University
* Update CHANGELOG
Run `./manage.py loadsources edu.columbia --overwrite` after merging on respective environments.

[SHARE-1011][Improvement] Add type map to Columbia Academic Commons

---

CHANGELOG.md
share/sources/uk.cambridge/source.yaml

University of Cambridge asked us to map some types.
* Add type mapping for University of Cambridge
* Update CHANGELOG
Run `./manage.py loadsources uk.cambridge --overwrite` after merging on respective environments.

[SHARE-1021][Improvement] Add type mapping for University of Cambridge

---

api/views/feeds.py
tests/api/test_feeds.py

At `/api/v2/atom`, each entry should have an `<author>` element like
```
<author><name>Steven Loria</name></author>
```
or 
```
<author><name>Steven Loria et al.</name></author>
```
but never `Loria, Steven`.
https://openscience.atlassian.net/browse/SHARE-1034

[SHARE-1034][Improvement] Use `name` instead of `cited_as` in atom feed

---

share/management/commands/fixpreprintdisambiguations.py

Update `fixpreprintdisambiguations` script to delete a work if all its identifiers have been removed.
https://openscience.atlassian.net/browse/SHARE-1059

[SHARE-1059] Delete works after removing all identifiers

---

share/oaipmh/repository.py

Using a subquery looked faster on staging, but still times out on production. Instead, do two queries so postgres doesn't get confused trying to optimize across both of them.

[SHARE-1045] Speed up OAI feed (for real this time)

---

api/normalizeddata/views.py
bots/elasticsearch/bot.py
osf_oauth2_adapter/provider.py
osf_oauth2_adapter/views.py
share/admin/jobs.py
share/bin/__init__.py
share/bin/util.py
share/graphql/agent.py
share/migrations/0049_jobs.py
share/models/core.py
share/models/creative.py
share/models/fields.py
share/models/fuzzycount.py
share/models/jobs.py
share/tasks/jobs.py
share/transformers/com_mendeley_data.py
share/util/__init__.py
tests/api/test_generated_endpoints.py
tests/share/normalize/factories.py
whitepapers/Tables.md
whitepapers/tasks/Ingest.md

Avoid having to create an index and constraint on the (rather large) normalized data table by using a many-to-many instead of a foreign key.
Also, make a stricter flake8 happy.

[SHARE-1051] Just a hair more migration optimization

---

share/harvesters/gov_nih.py
share/transformers/gov_nih.py

Change the NIH transformer to save `ORG_DEPT` as a tag, not as a "Department" agent in SHARE. `ORG_DEPT` comes from a controlled vocabulary, and doesn't necessarily correspond to an actual department (e.g. "MISCELLANEOUS", "OTHER HEALTH PROFESSIONS", "OTHER BASIC SCIENCES")
While testing this, I discovered NIH changed the date format on their website, so the harvester hasn't run successfully in some time. This PR also fixes that, and will raise a more understandable error should they change their date format again.
https://openscience.atlassian.net/browse/SHARE-1049

[SHARE-1049] Fix NIH harvester and department mapping

---

api/normalizeddata/views.py
api/search/views.py
api/views/feeds.py
api/views/workflow.py
bots/elasticsearch/bot.py
bots/elasticsearch/tasks.py
project/settings.py
share/graphql/query.py
share/search/__init__.py
share/search/daemon.py
share/tasks/jobs.py
share/util/graph.py
tests/conftest.py
tests/share/search/test_indexing.py
tests/share/tasks/test_ingest.py
tests/share/util/test_mutable_graph.py

When there's a large backlog of ingest or indexing tasks, freshly pushed data (e.g. new OSF preprints) go to the back of the queue and may have to wait a long while before they're available in the search index.
This PR adds new "urgent" queues for each bottleneck which allow pushed data to jump to the head of the line. Also, tidies up the elasticsearch settings, including removing the various (completely unused) "priority" settings.
New queue names:
- Ingest tasks: `ingest`, `ingest.urgent`
- Indexing to default search index: `es-share`, `es-share.urgent`
- Indexing to TritonSHARE search index: `es-triton-share`, `es-triton-share.urgent`
Deployment notes:
- Stop workers and wait until `es-index` and `es-index-firehose` queues are empty.
- After deployment, these queues can be deleted. …

[SHARE-1025] Add "urgent" queues

---

share/disambiguation/matcher.py
share/disambiguation/strategies/base.py
share/disambiguation/strategies/database.py
share/disambiguation/strategies/graph.py
share/management/commands/forceingest.py

Investigating some memory/performance issues locally yielded a few improvements that might help:
- Faster deduping algorithm for large input graphs
- Skip parsing/deduping unrealistically long names (>200 characters), seems that `nameparser` sometimes chokes
Also allow the `forceingest` script more retries before giving up.

Perf improvements

---

share/oaipmh/repository.py
tests/share/test_oaipmh.py

sometimes, if a complex-enough query is run on a large-enough table, postgres' planner throws up its hands in defeat and falls back to a more naive execution plan than we might expect.
existing (slow) query:
```sql
SELECT
table1.id,
-- (...more fields)
-- (...a bunch of aggregations with subqueries)
FROM table1
-- (...joins)
WHERE
-- (...conditions with subqueries)
LIMIT x
```
new (faster) query:
```sql
SELECT
table1.id,
-- (...more fields)
-- (...a bunch of aggregations with subqueries)
FROM table1
WHERE table1.id in (
SELECT t1.id
FROM table1 AS t1
-- (...joins)
WHERE
-- (...conditions with subqueries)
LIMIT x
)
```
moving the `LIMIT` and complex `WHERE` clause into a subquery guarantees that postgres won't run those aggregations on more rows than necessary

optimize oai-pmh query

---

.travis.yml
share/tasks/jobs.py

when creating new `IngestJob`s, we now have to schedule the
corresponding `ingest` celery task as well, thanks to a
decreasingly-temporary hack from a while back (see
commit d94757be0bfc15b42b26c30a6288af574c9aaf12)

[fix] after harvesting, schedule `ingest` tasks

---

share/schema/__init__.py
share/schema/exceptions.py
share/schema/loader.py
share/schema/schema-spec.yaml
share/schema/shapes.py
tests/share/schema/test_schema.py
tests/share/schema/test_schema_loader.py

add a static definition of the SHAREv2 schema, so we can start trimming tangles around all the `ShareObject` models
- `share/schema/schema-spec.yaml` contains the barest info actually needed by other code (mostly `share.util.graph` and `share.models.validators`)
- `share.schema.shapes` defines how the schema info will be structured
- `share.schema.loader` loads that yaml file and puts it in those structured shapes
- `share.schema.ShareV2Schema` ties the above together -- this is what consumers will import and use
things that are meaningfully different from the model-based SHAREv2 schema
- remove `ThroughContributors` (and `Contributor.contributed_through`) -- there are exactly `0` of these on production
- all fields are defined on the concrete type
- some fields in the model-based schema …

[ENG-1984] static schema

---

share/disambiguation/matcher.py
share/disambiguation/strategies/graph.py
share/ingest/change_builder.py
share/regulate/steps/__init__.py
share/regulate/steps/normalize_agent_names.py
share/util/graph.py
tests/share/util/test_mutable_graph.py

refactor `MutableGraph` and `MutableNode` in `share.util.graph` to get schema info from `share.schema` (new in #776) instead of from the `ShareObject` model classes (which will soon be deleted)
breaking changes in the public interface of `MutableGraph` and `MutableNode`:
- remove `MutableNode.model`, `MutableNode.concrete_model`
- instead, use the new `MutableNode.schema_type` to get type info in the form `share.schema.shapes::ShareV2SchemaType`
- remove `MutableGraph.filter_by_concrete_model`
- instead, use the new `MutableGraph.filter_by_concrete_type`, which takes a string instead of a model class
[ENG-1985]
[ENG-1985]: https://openscience.atlassian.net/browse/ENG-1985

[ENG-1985] use share.schema in share.util.graph

---

share/models/validators.py
tests/api/test_validator.py

trim another important dependency on the ShareObject family -- refactor `JSONLDValidator` in `share.models.validators` to get schema info from `share.schema` (new in #776) instead of from the `ShareObject` model classes (which will soon be deleted)
because `share.schema` has all fields defined on the concrete type (see #776), validation is now slightly looser in some cases -- attributes previously only valid for one subtype (e.g. `Person.given_name`) are now valid for all subtypes of that concrete type (e.g. `Organization`, `Institution`, `Consortium`, `Department`, and `Agent` may now also have a `given_name`)
i admit this is a little weird, but it probably will not matter.
[ENG-1986]
[ENG-1986]: https://openscience.atlassian.net/browse/ENG-1986

[ENG-1986] use share.schema in share.models.validators

---

api/normalizeddata/views.py
share/ingest/scheduler.py
share/janitor/tasks.py
share/management/commands/format_metadata_records.py
share/models/ingest.py
share/search/daemon.py
share/tasks/jobs.py
tests/factories/__init__.py
tests/share/models/test_suid.py
tests/share/tasks/test_ingest.py

add a `format_metadata_records` management command meant to be used when we add a new metadata format -- queues non-urgent ingest tasks for *all* suids that will generate FormattedMetadataRecords in the given format(s)
side effects:
- update ingestion logic to kinda pretend that ingest jobs and suids are already one-to-one -- always use the most recent RawDatum for the job's suid
- add `SourceUniqueIdentifier.ingest_job` to get most recent ingest job for a suid (will someday soon be replaced with a proper OneToOneField)
- add `SourceUniqueIdentifier.most_recent_raw_datum()`
- add ingest task params:
- `pls_format_metadata`: whether or not to follow the "new" FormattedMetadataRecord ingestion path (the "old" ShareObject path is controlled by the `apply_changes` param)
- `metadata_formats`: …

[ENG-2482] add format_metadata_records management command

---

api/urls.py
api/views/feeds.py
project/settings.py
tests/api/test_feeds.py
tests/conftest.py

- new atom/rss feeds:
- `/api/v2/feeds/atom/` (old: `/api/v2/atom/`)
- `/api/v2/feeds/rss/` (old: `/api/v2/atom/`)
- new feeds serve results from the `share_postrend_backcompat` index, while old feeds serve from `share_customtax_1`
- once we delete ShareObject, stop hard-coding index names and go back to using `settings.ELASTICSEARCH['PRIMARY_INDEX']` (or figure out something better)
- when `SHARE_LEGACY_PIPELINE` is set falsy, the old feeds will respond `410 Gone` to any request

[ENG-2740] add new feed URLs, make it easy to remove the old

---

api/banners/urls.py
api/formattedmetadatarecords/serializers.py
api/formattedmetadatarecords/urls.py
api/formattedmetadatarecords/views.py
api/normalizeddata/views.py
api/sourceconfigs/serializers.py
api/sourceconfigs/urls.py
api/sourceconfigs/views.py
api/sources/serializers.py
api/suids/serializers.py
api/suids/urls.py
api/suids/views.py
api/urls.py
share/models/core.py
share/models/ingest.py
share/models/validators.py
share/transform/chain/links.py

- expose some models in the api:
- `/api/v2/formattedmetadatarecords/`
- `/api/v2/sourceconfigs/`
- `/api/v2/suids/`
- make the api a little more consistent (for ease of frontend changes)
- handle `localhost:port` urls in DEBUG mode (for ease of local testing)
blocks CenterForOpenScience/ember-share#216

[ENG-2650] give the frontend enough to display something useful for each suid

---

Dockerfile

* Prior image was based on Debian stretch, which reached EOL on July
1, 2022[1]. Update to buster, which will be supported until June
30, 2024.
* Remove `gosu` installation step. `gosu` could have been installed
via apt-get on Debian buster but appears to no longer be used.
[1] https://lwn.net/Articles/899962/

update Dockerfile to be based on Debian buster

---

.github/workflows/run_tests.yml
Dockerfile
api/middleware.py
api/normalizeddata/views.py
api/views/feeds.py
docker-compose.yml
project/celery.py
project/logging_formatter.py
project/settings.py
requirements.txt
share/celery.py
share/search/daemon.py
share/search/index_messenger.py
tests/share/search/index_strategy/_with_real_services.py
tests/share/search/test_daemon.py

- downgrade to python 3.10 (for now)
- upgrade to `sentry-sdk` (from `raven`)
- add log formatter to produce single-line json (when not in debug mode)
- tidy some code

[fix] upgrade/downgrade for compatibile dependencies

---

share/search/search_params.py
trove/trovesearch_gathering.py
trove/vocab/osfmap.py
trove/vocab/trove.py

each `related-property-path` included with an `index-card-search` response now comes with a `suggestedFilterOperator` attribute that could be used in another `index-card-search` request with the query param `cardSearchFilter[<propertyPathKey>][<suggestedFilterOperator>]`
e.g. the following suggests that adding `cardSearchFilter[supplements][is-present]` to the current search would yield 1 result
```js
{
"id": "...",
"type": "related-property-path",
"attributes": {
"propertyPathKey": "supplements"
"suggestedFilterOperator": "is-present",
"cardSearchResultCount": 1,
// ...
}
},
```
suggests `"at-date"` for date properties, `"is-present"` for "boolean filter facets", and `"any-of"` to recommend an `index-value-search` to find valid iri values to filter by
(ticket: [ENG-4657])
[ENG-4657]: …

[ENG-4657] add suggestedFilterOperator

---

share/search/index_strategy/trove_indexcard_flats.py
share/search/search_params.py

allow filtering `index-value-search` by value iri (with `valueSearchFilter[sameAs]`) and type (with `valueSearchFilter[resourceType]`
e.g.
```
GET /api/v3/index-value-search
?valueSearchPropertyPath=rights
&valueSearchFilter[sameAs]=https%3A//creativecommons.org/publicdomain/zero/1.0/legalcode
```
```
GET /api/v3/index-value-search
?valueSearchPropertyPath=creator
&valueSearchFilter[resourceType]=Person
```
[ENG-4661]
[ENG-4661]: https://openscience.atlassian.net/browse/ENG-4661?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-4661] allow filtering `index-value-search` by value iri and type

---

share/models/feature_flag.py
share/search/index_strategy/trove_indexcard_flats.py
share/search/search_params.py
tests/_testutil.py
tests/share/search/test_search_params.py
trove/trovesearch_gathering.py
trove/vocab/osfmap.py
trove/vocab/trove.py

breaking change behind a feature flag (`periodic_propertypaths`)
change how property paths are serialized in query params:
- use `.` (period) to delimit path-steps, e.g. `creator.affiliation`
parsed as one path of two steps (previously `creator,affiliation`)
- use `,` (comma) to delimit multiple paths, e.g.
`creator.affiliation,contributor.affiliation` parsed as two paths of
two steps (previously impossible)

support filtering across multiple propertypaths

---

project/settings.py
requirements.txt

- bump celery to 5.4.0 (from 5.1.2)
- bump kombu to 5.3.7 (from 5.1.0)
- bump python-dateutil to 2.9.0 (from 2.8.1)
- bump django-allauth to 0.63.6 (from 0.44.0)

[ENG-6072] fix ci

---

trove/vocab/osfmap.py

Enable search faceting for "Subject" on Projects
- Added the (DCTERMS.subject,) field to the PROJECT_SUGGESTED_PROPERTY_PATHS in the osfmap.py file. 
[ENG-5992](https://openscience.atlassian.net/browse/ENG-5992)
[ENG-5992]: https://openscience.atlassian.net/browse/ENG-5992?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-5992] Add Subject facet to project search filters

---

tests/trove/derive/_base.py
tests/trove/derive/_inputs.py
tests/trove/derive/test_oaidcxml.py
tests/trove/derive/test_osfmap_json.py
tests/trove/derive/test_sharev2_elastic.py
trove/derive/osfmap_json.py
trove/vocab/osfmap.py

- add shorthands for new osfmap metadata properties:
- `qualifiedAttribution`
- `agent`
- `hadRole`
- `usage`
- `storageRegion`
- `storageByteCount`
- `hasOsfAddon`
- `viewCount`
- `viewSessionCount`
- `downloadCount`
- `downloadSessionCount`
- `temporalCoverage`
- update `osfmap_json` deriver
- consistently compact `@id` and `@type` iris
- consistent value ordering
- add test cases; add tests at all for `trove.derive.osfmap_json`

[ENG-6190] add to (and improve) osfmap-json shorthand

---

osf_oauth2_adapter/adapters.py
osf_oauth2_adapter/provider.py
osf_oauth2_adapter/views.py
project/settings.py

smooth out some hacks to work with slightly updated `django-allauth`
(in allauth, "oauth2 adapters" and "social account adapters" are different things with overlapping name that (by happenstance, previously) were non-overlapping enough they could be merged into a single subclass without much problem -- alas, no longer)

[ENG-6508] fix: two few adapters

---

share/search/index_strategy/trove_indexcard_flats.py
tests/trove/derive/_base.py
tests/trove/digestive_tract/test_extract.py
trove/derive/_base.py
trove/digestive_tract.py
trove/models/indexcard.py

add `as_rdfdoc_with_supplements` method to `IndexcardRdf` models; use consistently when getting rdf content of an indexcard for indexing or derivation
[ENG-6521]
[ENG-6521]: https://openscience.atlassian.net/browse/ENG-6521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-6521] fix: include supplements in indexed data

---

share/search/index_strategy/_base.py
share/search/index_strategy/elastic8.py
share/search/index_strategy/trovesearch_denorm.py
share/search/messages.py
share/tasks/__init__.py
tests/share/search/index_strategy/_common_trovesearch_tests.py
trove/models/indexcard.py
trove/trovesearch/search_params.py

follow-up to #828 
- fix `trovesearch_denorm` error loading related property counts (with tests)
- improve `trovesearch_denorm`'s handling of removed values:
- add `chunk_timestamp` field
- instead of deleting all value-docs before each chunk, use `chunk_timestamp` to delete only the value-docs not 
updated _after_ each chunk
- add tests for de-indexing cards and values
- remove some dead code

[ENG-6189] denorm fixes/followup

---

share/search/index_strategy/_trovesearch_util.py

fix(trovesearch_denorm): whole-iris field names
retain the entire iri for path-based field names --
this makes them easily reversible for highlighting fields that match
(previously used "sufficiently unique" iris like "://foo.example/blarg",
which works well enough, except it'd take knowledge to get the original -- see e.g. `://purl.org/dc/terms/description` in search results' "Context" at https://staging.osf.io/search?q=miscellaneous )
(bug introduced in 7b68b96529864e94003519841aa15faac385b2e0 )

fix: retain entire iris in dynamic field names

---

share/search/daemon.py

improve the indexer daemon's handling of connection errors with rabbit
- set `heartbeat` on the kombu connection
- use `kombu.Connection.ensure` and `kombu.Connection.autoretry` to
better handle errors when consuming or acking messages

[ENG-6654] indexer recover from connection errors

---

docker-compose.yml
project/settings.py
share/search/daemon.py
share/search/index_strategy/elastic8.py
share/search/index_strategy/trovesearch_denorm.py
share/search/messages.py
tests/share/search/index_strategy/_with_real_services.py
tests/share/search/index_strategy/test_trovesearch_denorm.py

- partly revert #835 (remove `ensure_ack`, `ack_callback`) -- messages can _only_ be ack'd thru the channel they were received by, so trying to recover a channel to ack thru does nothing
- handle easily-detectable delete_by_query conflicts in a followup celery task (so the indexer doesn't fall over on it)
- local setup: allow the worker's `daemon` user to access elastic8
- update consumer prefetch limit to match the indexing chunk size (seems to avoid connection errors, [maybe this is why](https://stackoverflow.com/a/36114095))
- try avoiding connection errors when calling `message.ack()` -- do a bit more book-keeping to know when a bulk elastic action is the last for its index-card, so it can ack immediately then instead of waiting 'til the whole chunk has completed
- test updates to …

[ENG-6654] fixfix: correct misunderstanding, handle conflicts

---

share/models/feature_flag.py
trove/vocab/osfmap.py

when feature flag PREPRINT_AFFILIATIONS is up, suggest `affiliation` instead of `creator.affiliation` for searching preprints

[ENG-5907] osfmap: suggest `affiliation` for preprints

---

share/search/index_strategy/trovesearch_denorm.py
trove/trovesearch/search_params.py

when getting highlighted snippets/"evidence" for search results, omit fields that are not present in the original query

[ENG-6708] fix: omit irrelevant search-result evidence/highlights

---

share/search/index_strategy/trovesearch_denorm.py

Add query syntax with `simple_query_string`
https://openscience.atlassian.net/browse/ENG-7429

[ENG-7429] Add query syntax with `simple_query_string

---

share/management/commands/delete_pretrove_data.py

fix `delete_pretrove_data` command to leave trove data undeleted (post-trove rdf-ingesting sourceconfigs have null `transformer_key`, not `transformer_key="rdf"`)

fix: trove sourceconfigs have null transformer_key

---

share/management/commands/delete_pretrove_data.py

update `delete_pretrove_data` management command to accept `--chunksize` param (default 1024) and delete data in small chunks (and from one sourceconfig at a time) instead of deleting all-at-once
local (contrived) example:
```
root@eac74ef154f9:/code# python manage.py delete_pretrove_data
pre-trove source-configs with deletable rawdata:
system.v2_push
really DELETE ALL raw metadata records belonging to these source-configs? (y/n)y
system.v2_push: deleting all rawdata...
system.v2_push: deleted 1024
system.v2_push: deleted 1024
system.v2_push: deleted 1024
system.v2_push: deleted 1024
system.v2_push: deleted 904
system.v2_push: done; deleted 5000
deleted 5000 items
root@eac74ef154f9:/code# python manage.py delete_pretrove_data
nothing to delete
```
[ENG-7922]
[ENG-7922]: …

[ENG-7922] chunky delete_pretrove_data (and --chunksize param)

---

trove/vocab/osfmap.py

`suggestedFilterOperator` should be json-serialized without a prefix (e.g. "is-present", "any-of", "at-date") but are now prefixed with trove: ("trove:is-present", "trove:any-of", "trove:at-date"), which breaks parts of osf frontend search
this fix adds filter-operators to `trove.vocab.osfmap.OSFMAP_THESAURUS` so `osfmap_json_shorthand()` correctly abbreviates them without prefix (...more robust/consistent namespace handling is beyond scope...)
see [example json](https://staging-share.osf.io/trove/index-card-search?cardSearchFilter%5BresourceType%5D=Registration&include=trove%3ArelatedPropertyList&acceptMediatype=application%2Fvnd.api%2Bjson) (search "suggestedFilterOperator" -- values should not begin with "trove:")
[ENG-8050]
[ENG-8050]: …

[ENG-8050] fix: unprefix suggestedFilterOperator

---

share/search/index_strategy/sharev2_elastic8.py

fix a bug in `sharev2_elastic8` that caused the indexer daemon to leave some messages un-acked, which eventually prevents it from fetching more
(note: fix is only the first arg to `_make_actionset`, which should always be the given id regardless of "backcompat" magic -- renamed local var only to clarify for the reader)

fix: inackurate messaging

---

tests/trove/derive/test_osfmap_json.py
tests/trove/derive/test_osfmap_json_mini.py
tests/trove/digestive_tract/test_derive.py
trove/derive/__init__.py
trove/derive/osfmap_json.py
trove/derive/osfmap_json_mini.py
trove/models/indexcard.py

Added IndexcardJsonDeriver
https://openscience.atlassian.net/browse/ENG-7445

[ENG-7445] Added IndexcardJsonDeriver

---

tests/trove/derive/test_osfmap_json_mini.py
trove/derive/osfmap_json_mini.py
trove/util/trove_params.py
trove/vocab/osfmap.py

- correct `osf:verifiedLink` (previously `osf:verifiedLinks`)
- correct `dcat:accessURL` (previously `dcat:accessUrl`)
- in the "mini" osfmap json representation, use an "excluded" set instead of an "included" set, so newly added properties are included by default
- (incidental) allow `fields=...` api query parameter for TSV/CSV columns (same as `fields[*]=...`)
[ENG-8287]
[ENG-8287]: https://openscience.atlassian.net/browse/ENG-8287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[ENG-8287] Fix/osfmap mismatches
